package Vista;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 * Clase principal de la vista del sistema.
 *
 * <p>
 * Esta clase actúa como contenedor principal de la interfaz gráfica utilizando
 * el patrón CardLayout para navegar entre las diferentes pantallas:
 * Bienvenida, Juego y Resultados.
 * </p>
 *
 * Responsabilidades:
 * - Inicializar la ventana principal
 * - Gestionar el cambio entre paneles (pantallas)
 * - Mostrar recursos visuales generales
 *
 * No contiene lógica del juego (MVC).
 *
 * @author Juan
 * @version 1.0
 */
public class Vista extends javax.swing.JFrame {
    
    /** Layout para cambiar entre pantallas */
    private CardLayout cardLayout;
    
    /**
     * Constructor principal.
     * Configura propiedades básicas de la ventana.
     */
    public Vista() {
        initComponents();
        configurarVentana();
        cargarImagenEscalada(jLabelBalero, "/images/Balero.png");
    }
    
    /**
     * Configuración general del JFrame.
     */
    private void configurarVentana() {
        this.setTitle("Juego del Balero");
        this.setSize(900, 700);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
    }
    /**
     * Permite cambiar entre las diferentes pantallas.
     *
     * @param nombrePanel Nombre registrado en el CardLayout:
     *                    "Bienvenida", "Juego", "Resultado"
     */
    public void mostrarPanel(String nombrePanel) {
        cardLayout.show(getContentPane(), nombrePanel);
    }
    
    /**
     * Carga una imagen desde los recursos del proyecto y la ajusta al tamaño del JLabel.
     *
     * <p>
     * Código basado en prácticas recomendadas de manejo de recursos en Swing.
     * Adaptado para el proyecto Juego del Balero.
     * Fuente: Documentación oficial de Oracle - ImageIcon.
     * </p>
     *
     * @param label JLabel donde se mostrará la imagen
     * @param ruta  Ruta dentro del classpath (ej: /images/balero.png)
     */
    private void cargarImagenEscalada(JLabel label, String ruta) {
        try {
            ImageIcon iconoOriginal = new ImageIcon(getClass().getResource(ruta));
            Image imagen = iconoOriginal.getImage().getScaledInstance(
                    label.getWidth(),
                    label.getHeight(),
                    Image.SCALE_SMOOTH
            );
            Icon icono = new ImageIcon(imagen);
            label.setIcon(icono);
        } catch (Exception e) {
            System.out.println("No se pudo cargar la imagen: " + ruta);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unckecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelBalero = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jTextFieldTiempo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelJuego = new javax.swing.JPanel();
        jPanelEquipo = new javax.swing.JPanel();
        jPanelJugador = new javax.swing.JPanel();
        jPanelResultado = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelBienvenida.setBackground(new java.awt.Color(185, 151, 151));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("¡BIENVENIDO AL JUEGO DEL BALERO!");

        jLabelBalero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Specs/Imagenes/Balero.png"))); // NOI18N

        jButtonIniciar.setText("INICIAR");

        jButtonCargar.setText("CARGAR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("INGRESE EL TIEMPO DE JUEGO (EN SEGUNDOS)");

        javax.swing.GroupLayout jPanelBienvenidaLayout = new javax.swing.GroupLayout(jPanelBienvenida);
        jPanelBienvenida.setLayout(jPanelBienvenidaLayout);
        jPanelBienvenidaLayout.setHorizontalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                .addGroup(jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jButtonIniciar)
                            .addGap(161, 161, 161)
                            .addComponent(jButtonCargar))
                        .addGroup(jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2))))
                    .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelBalero, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBienvenidaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanelBienvenidaLayout.setVerticalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBienvenidaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBalero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jTextFieldTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciar)
                    .addComponent(jButtonCargar))
                .addGap(23, 23, 23))
        );

        jButtonIniciar.getAccessibleContext().setAccessibleName("Iniciar");
        jButtonCargar.getAccessibleContext().setAccessibleName("Cargar");

        getContentPane().add(jPanelBienvenida, "Bienvenida");

        jPanelJuego.setBackground(new java.awt.Color(204, 255, 204));
        jPanelJuego.setLayout(new java.awt.GridLayout());

        jPanelEquipo.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout jPanelJugadorLayout = new javax.swing.GroupLayout(jPanelJugador);
        jPanelJugador.setLayout(jPanelJugadorLayout);
        jPanelJugadorLayout.setHorizontalGroup(
            jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPanelJugadorLayout.setVerticalGroup(
            jPanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        jPanelEquipo.add(jPanelJugador);
        jPanelJugador.getAccessibleContext().setAccessibleName("Jugador");

        jPanelJuego.add(jPanelEquipo);
        jPanelEquipo.getAccessibleContext().setAccessibleName("Equipo");

        getContentPane().add(jPanelJuego, "Juego");

        jPanelResultado.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelResultado, "Resultado");

        pack();
    }// </editor-fold>//GEN-END:initComponents
// ================= MÉTODOS DE ACCESO (para el controlador) =================

    public javax.swing.JButton getBtnIniciar() {
        return jButtonIniciar;
    }

    public javax.swing.JButton getBtnCargar() {
        return jButtonCargar;
    }

    public javax.swing.JPanel getPanelJuego() {
        return jPanelJuego;
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBalero;
    private javax.swing.JPanel jPanelBienvenida;
    private javax.swing.JPanel jPanelEquipo;
    private javax.swing.JPanel jPanelJuego;
    private javax.swing.JPanel jPanelJugador;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JTextField jTextFieldTiempo;
    // End of variables declaration//GEN-END:variables
}
